#include "aeromesh/reed_solomon.hpp"

#include <array>
#include <cstring>

namespace aeromesh {
namespace {

// --- GF(2^8) arithmetic ------------------------------------------------------
// Field generated by the primitive polynomial 0x11d (x^8+x^4+x^3+x^2+1) with
// 2 as a generator. exp/log tables are built once at first use.
struct GfTables {
    std::array<std::uint8_t, 512> exp{};  // doubled to avoid mod on multiply
    std::array<std::uint8_t, 256> log{};
    GfTables() {
        int x = 1;
        for (int i = 0; i < 255; ++i) {
            exp[i] = static_cast<std::uint8_t>(x);
            log[x] = static_cast<std::uint8_t>(i);
            x <<= 1;
            if (x & 0x100)
                x ^= 0x11d;
        }
        for (int i = 255; i < 512; ++i)
            exp[i] = exp[i - 255];
    }
};

const GfTables& gf() {
    static const GfTables t;
    return t;
}

std::uint8_t gf_mul(std::uint8_t a, std::uint8_t b) {
    if (a == 0 || b == 0)
        return 0;
    const GfTables& t = gf();
    return t.exp[t.log[a] + t.log[b]];
}

std::uint8_t gf_div(std::uint8_t a, std::uint8_t b) {
    // Caller guarantees b != 0.
    if (a == 0)
        return 0;
    const GfTables& t = gf();
    int d = t.log[a] - t.log[b];
    if (d < 0)
        d += 255;
    return t.exp[d];
}

// a raised to the power n in GF(256). pow(0,0) == 1, pow(0,n>0) == 0.
std::uint8_t gf_pow(std::uint8_t a, int n) {
    std::uint8_t result = 1;
    std::uint8_t base = a;
    while (n > 0) {
        if (n & 1)
            result = gf_mul(result, base);
        base = gf_mul(base, base);
        n >>= 1;
    }
    return result;
}

// --- small dense matrices over GF(256), row-major ----------------------------
using Mat = std::vector<std::uint8_t>;

// Invert an n x n matrix in place via Gauss-Jordan. Returns false if singular.
bool invert(Mat& m, int n) {
    // Augment [m | I] conceptually; track the identity in a second buffer.
    Mat inv(static_cast<std::size_t>(n) * n, 0);
    for (int i = 0; i < n; ++i)
        inv[static_cast<std::size_t>(i) * n + i] = 1;

    for (int col = 0; col < n; ++col) {
        // Find a pivot row at or below `col` with a non-zero entry.
        int pivot = -1;
        for (int r = col; r < n; ++r) {
            if (m[static_cast<std::size_t>(r) * n + col] != 0) {
                pivot = r;
                break;
            }
        }
        if (pivot < 0)
            return false;

        if (pivot != col) {
            for (int c = 0; c < n; ++c) {
                std::swap(m[static_cast<std::size_t>(col) * n + c],
                          m[static_cast<std::size_t>(pivot) * n + c]);
                std::swap(inv[static_cast<std::size_t>(col) * n + c],
                          inv[static_cast<std::size_t>(pivot) * n + c]);
            }
        }

        // Scale the pivot row so the pivot becomes 1.
        std::uint8_t pv = m[static_cast<std::size_t>(col) * n + col];
        for (int c = 0; c < n; ++c) {
            m[static_cast<std::size_t>(col) * n + c] =
                gf_div(m[static_cast<std::size_t>(col) * n + c], pv);
            inv[static_cast<std::size_t>(col) * n + c] =
                gf_div(inv[static_cast<std::size_t>(col) * n + c], pv);
        }

        // Eliminate this column from every other row.
        for (int r = 0; r < n; ++r) {
            if (r == col)
                continue;
            std::uint8_t factor = m[static_cast<std::size_t>(r) * n + col];
            if (factor == 0)
                continue;
            for (int c = 0; c < n; ++c) {
                m[static_cast<std::size_t>(r) * n + c] ^=
                    gf_mul(factor, m[static_cast<std::size_t>(col) * n + c]);
                inv[static_cast<std::size_t>(r) * n + c] ^=
                    gf_mul(factor, inv[static_cast<std::size_t>(col) * n + c]);
            }
        }
    }
    m = std::move(inv);
    return true;
}

} // namespace

std::expected<ReedSolomon, RsError> ReedSolomon::create(int data_shards,
                                                       int parity_shards) {
    if (data_shards < 1 || parity_shards < 0 ||
        data_shards + parity_shards > 255)
        return std::unexpected(RsError::InvalidParams);

    ReedSolomon rs;
    rs.data_shards_ = data_shards;
    rs.parity_shards_ = parity_shards;

    const int n = data_shards + parity_shards;
    const int k = data_shards;

    // Build a Vandermonde matrix V (n x k): V[r][c] = r^c in GF(256).
    Mat vander(static_cast<std::size_t>(n) * k, 0);
    for (int r = 0; r < n; ++r)
        for (int c = 0; c < k; ++c)
            vander[static_cast<std::size_t>(r) * k + c] =
                gf_pow(static_cast<std::uint8_t>(r), c);

    // top = first k rows of V; invert it.
    Mat top(static_cast<std::size_t>(k) * k, 0);
    for (int r = 0; r < k; ++r)
        for (int c = 0; c < k; ++c)
            top[static_cast<std::size_t>(r) * k + c] =
                vander[static_cast<std::size_t>(r) * k + c];
    if (!invert(top, k))
        return std::unexpected(RsError::SingularMatrix);

    // encoding matrix = V * top^{-1}; its top k rows become the identity,
    // making the code systematic.
    rs.matrix_.assign(static_cast<std::size_t>(n) * k, 0);
    for (int r = 0; r < n; ++r) {
        for (int c = 0; c < k; ++c) {
            std::uint8_t acc = 0;
            for (int i = 0; i < k; ++i)
                acc ^= gf_mul(vander[static_cast<std::size_t>(r) * k + i],
                              top[static_cast<std::size_t>(i) * k + c]);
            rs.matrix_[static_cast<std::size_t>(r) * k + c] = acc;
        }
    }
    return rs;
}

std::expected<void, RsError> ReedSolomon::encode(
    std::vector<std::vector<std::byte>>& shards) const {
    const int n = total_shards();
    const int k = data_shards_;
    if (static_cast<int>(shards.size()) != n)
        return std::unexpected(RsError::InvalidParams);

    const std::size_t len = shards[0].size();
    for (int i = 0; i < n; ++i) {
        if (i < k && shards[i].size() != len)
            return std::unexpected(RsError::ShardSizeMismatch);
    }
    for (int r = k; r < n; ++r)
        shards[r].assign(len, std::byte{0});

    for (int r = k; r < n; ++r) {
        for (int j = 0; j < k; ++j) {
            const std::uint8_t coeff =
                matrix_[static_cast<std::size_t>(r) * k + j];
            if (coeff == 0)
                continue;
            const auto& src = shards[j];
            auto& dst = shards[r];
            for (std::size_t p = 0; p < len; ++p)
                dst[p] ^= static_cast<std::byte>(
                    gf_mul(coeff, static_cast<std::uint8_t>(src[p])));
        }
    }
    return {};
}

std::expected<void, RsError> ReedSolomon::reconstruct(
    std::vector<std::vector<std::byte>>& shards,
    const std::vector<bool>& present) const {
    const int n = total_shards();
    const int k = data_shards_;
    if (static_cast<int>(shards.size()) != n ||
        static_cast<int>(present.size()) != n)
        return std::unexpected(RsError::InvalidParams);

    // Determine shard length and validate present shards agree.
    std::size_t len = 0;
    bool have_len = false;
    int present_count = 0;
    for (int i = 0; i < n; ++i) {
        if (!present[i])
            continue;
        ++present_count;
        if (!have_len) {
            len = shards[i].size();
            have_len = true;
        } else if (shards[i].size() != len) {
            return std::unexpected(RsError::ShardSizeMismatch);
        }
    }
    if (present_count < k)
        return std::unexpected(RsError::TooFewShards);
    if (present_count == n)
        return {};  // nothing missing

    // Pick the first k present shards; their encoding-matrix rows form the
    // decode system.
    std::vector<int> use;
    use.reserve(k);
    for (int i = 0; i < n && static_cast<int>(use.size()) < k; ++i)
        if (present[i])
            use.push_back(i);

    Mat sub(static_cast<std::size_t>(k) * k, 0);
    for (int r = 0; r < k; ++r)
        for (int c = 0; c < k; ++c)
            sub[static_cast<std::size_t>(r) * k + c] =
                matrix_[static_cast<std::size_t>(use[r]) * k + c];
    if (!invert(sub, k))
        return std::unexpected(RsError::SingularMatrix);

    // Reconstruct any missing DATA shard i as a linear combination of the k
    // chosen present shards: data[i] = sum_p sub^{-1}[i][p] * shard[use[p]].
    for (int i = 0; i < k; ++i) {
        if (present[i])
            continue;
        std::vector<std::byte> out(len, std::byte{0});
        for (int p = 0; p < k; ++p) {
            const std::uint8_t coeff =
                sub[static_cast<std::size_t>(i) * k + p];
            if (coeff == 0)
                continue;
            const auto& src = shards[use[p]];
            for (std::size_t b = 0; b < len; ++b)
                out[b] ^= static_cast<std::byte>(
                    gf_mul(coeff, static_cast<std::uint8_t>(src[b])));
        }
        shards[i] = std::move(out);
    }

    // Recompute any missing PARITY shards now that all data shards are present.
    for (int r = k; r < n; ++r) {
        if (present[r])
            continue;
        std::vector<std::byte> out(len, std::byte{0});
        for (int j = 0; j < k; ++j) {
            const std::uint8_t coeff =
                matrix_[static_cast<std::size_t>(r) * k + j];
            if (coeff == 0)
                continue;
            const auto& src = shards[j];
            for (std::size_t b = 0; b < len; ++b)
                out[b] ^= static_cast<std::byte>(
                    gf_mul(coeff, static_cast<std::uint8_t>(src[b])));
        }
        shards[r] = std::move(out);
    }
    return {};
}

} // namespace aeromesh
